import { BookOpen, CalendarDays, CalendarClock, Check, Church, Clock3, DatabaseBackup, FileText, Globe, Heart, HeartHandshake, LayoutDashboard, LockKeyhole, MapPin, MessageCircle, MessagesSquare, Monitor, Newspaper, Palette, Pencil, RefreshCcw, Repeat2, Rocket, Search, Settings2, ShieldCheck, Smartphone, SlidersHorizontal, Users, UsersRound, Video } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { FaqAccordion } from "@/components/landing/faq-accordion";
import { LeadForm } from "@/components/landing/lead-form";
import { ProductTabs } from "@/components/landing/product-tabs";
import { ScrollProgress } from "@/components/motion/scroll-progress";

type IconType = LucideIcon;
const painPoints: Array<[IconType, string, string]> = [[Globe, "Site antigo ou inexistente", "Informações importantes ficam difíceis de encontrar ou simplesmente não estão disponíveis online."], [RefreshCcw, "Atualizações complicadas", "Cada pequena alteração depende de alguém com conhecimento técnico ou de um fornecedor externo."], [MessagesSquare, "Informações espalhadas", "Instagram, WhatsApp, Facebook, cartazes e grupos assumem funções diferentes sem um ponto central."], [CalendarClock, "Horários desatualizados", "Missas, confissões, secretaria e eventos mudam, mas atualizar todos os canais dá trabalho."], [Repeat2, "Perguntas repetitivas", "A secretaria responde diversas vezes informações que poderiam estar disponíveis com clareza."], [Users, "Dependência de poucas pessoas", "Quando quem cuida da comunicação não está disponível, a presença digital pode parar."]];
const features: Array<[IconType, string, string]> = [[Church, "Horários de celebrações", "Organize missas, confissões e atividades de maneira fácil de consultar."], [CalendarDays, "Agenda paroquial", "Centralize eventos, encontros, celebrações especiais e atividades."], [Newspaper, "Notícias e comunicados", "Publique avisos sem depender exclusivamente das redes sociais."], [UsersRound, "Pastorais e movimentos", "Apresente pastorais, responsáveis, atividades e formas de participação."], [BookOpen, "Sacramentos", "Organize orientações, horários, documentos e informações importantes."], [MapPin, "Comunidades e capelas", "Apresente igrejas, capelas, endereços e horários vinculados."], [FileText, "Documentos e informações", "Disponibilize materiais importantes de maneira organizada."], [MessageCircle, "Contato facilitado", "Ajude o visitante a encontrar secretaria, endereço e canais oficiais."], [Video, "Transmissões e conteúdos", "Organize transmissões, vídeos e conteúdos da comunidade."], [HeartHandshake, "Contribuições e doações", "Quando habilitado, disponibilize caminhos seguros para contribuições."]];
const benefits: Array<[IconType, string, string]> = [[Search, "Informação mais fácil de encontrar", "Quem procura horários, endereço ou eventos encontra tudo em um lugar organizado."], [Clock3, "Menos trabalho repetitivo", "Informações bem organizadas reduzem perguntas simples e tarefas recorrentes."], [Smartphone, "Uma experiência melhor no celular", "O site nasce preparado para o dispositivo usado diariamente."], [RefreshCcw, "Conteúdo sempre atualizável", "A presença digital acompanha a vida da comunidade."], [ShieldCheck, "Mais controle", "A paróquia ganha uma estrutura própria para suas informações."], [Heart, "Mais proximidade", "A tecnologia ajuda a comunidade a encontrar o que precisa para participar."]];
const faq: Array<[string, string]> = [["O Católico Digital é apenas um site?", "Não. O site é uma parte da solução: a proposta é organizar a presença digital da paróquia e facilitar sua manutenção."], ["Nossa paróquia já possui um site. Podemos utilizar o Católico Digital?", "Sim. Cada caso pode ser analisado para entender quais conteúdos podem ser aproveitados ou reorganizados."], ["É necessário entender de tecnologia?", "A proposta é justamente reduzir essa necessidade e simplificar a administração das informações principais."], ["Podemos utilizar nosso próprio domínio?", "A estrutura prevê a possibilidade de domínio próprio. Os detalhes são definidos durante a implantação."], ["O site funciona no celular?", "Sim. A experiência é planejada com abordagem mobile-first para smartphones, tablets e computadores."], ["Todas as paróquias precisam utilizar os mesmos recursos?", "Não. Os recursos podem ser organizados conforme a realidade e necessidade de cada comunidade."], ["Quanto custa?", "Durante o lançamento, as modalidades comerciais e condições de implantação serão apresentadas diretamente às paróquias interessadas."], ["Existe suporte?", "O modelo de suporte fará parte da modalidade contratada e será explicado antes da contratação."]];
const tabs = [{ label: "Site", title: "Uma presença digital clara, organizada e preparada para qualquer tela.", description: "Homepage, horários, agenda e notícias em uma experiência única para a comunidade.", kind: "site" }, { label: "Agenda", title: "Eventos e celebrações organizados para facilitar a consulta.", description: "A informação certa aparece no momento em que a comunidade precisa dela.", kind: "agenda" }, { label: "Conteúdo", title: "Publique notícias sem transformar cada atualização em tarefa técnica.", description: "Conteúdo com contexto, autoria e organização para durar além de uma postagem.", kind: "content" }, { label: "Administração", title: "Uma área simples para cuidar das informações mais importantes.", description: "A paróquia continua no controle daquilo que publica e atualiza.", kind: "admin" }];
const steps: Array<[string, string, string, IconType]> = [["01", "Conhecemos a paróquia", "Reunimos informações, necessidades, identidade e conteúdos necessários.", UsersRound], ["02", "Preparamos a presença digital", "Organizamos identidade, páginas, informações e recursos.", Palette], ["03", "Publicamos", "O site é preparado, revisado e disponibilizado para a comunidade.", Rocket], ["04", "A paróquia continua no controle", "As informações podem ser atualizadas conforme a necessidade.", Settings2]];
const security: Array<[IconType, string, string]> = [[ShieldCheck, "Conexão segura", "HTTPS e infraestrutura configurada com boas práticas."], [DatabaseBackup, "Backups", "Rotinas de backup ajudam a proteger informações importantes."], [UsersRound, "Controle de acesso", "Áreas administrativas são protegidas para pessoas autorizadas."], [LockKeyhole, "Privacidade", "O projeto considera princípios e requisitos aplicáveis da LGPD."]];

function IconCard({ icon: Icon, title, copy, className = "" }: { icon: IconType; title: string; copy: string; className?: string }) { return <article className={`icon-card ${className}`.trim()}><span className="icon-card__icon"><Icon aria-hidden="true" size={22} strokeWidth={1.7} /></span><h3>{title}</h3><p>{copy}</p></article>; }
function cards(items: Array<[IconType, string, string]>) { return items.map(([Icon, title, copy]) => <IconCard key={title} icon={Icon} title={title} copy={copy} />); }

export function LandingPage() {
  return <main id="main-content"><ScrollProgress />
    <section className="hero hero--brand landing-hero" aria-labelledby="hero-title"><div className="hero-pattern" aria-hidden="true" /><Container className="hero__grid"><div className="hero__content"><p className="eyebrow eyebrow--light">Tecnologia pensada para paróquias</p><h1 id="hero-title">Uma presença digital <span>à altura da sua paróquia.</span></h1><p className="hero-copy hero-copy--light">Tenha site, informações, agenda, notícias e comunicação organizados em um só lugar — de forma simples, atual e fácil de manter.</p><div className="hero__actions"><Link className="button button--gold" href="#quero-conhecer">Quero conhecer o Católico Digital</Link><Link className="text-link text-link--light" href="#como-funciona"><span className="play-icon" aria-hidden="true">▶</span> Veja como funciona</Link></div><p className="hero-microcopy">Pensado para paróquias que querem cuidar melhor da sua presença no digital.</p></div><div className="product-preview product-preview--composed" role="img" aria-label="Prévia ilustrativa do site paroquial no Católico Digital"><div className="device-window"><div className="device-window__bar"><span /><span /><span /></div><div className="device-window__screen"><div className="screen-nav" /><div className="screen-hero" /><div className="screen-blocks"><i /><i /><i /></div></div></div><div className="floating-card floating-card--celebration"><Church aria-hidden="true" size={15} /><span>Próxima celebração<strong>19h · Santa Missa</strong></span></div><div className="floating-card floating-card--news"><Newspaper aria-hidden="true" size={15} /><span>Nova notícia<strong>Publicada agora</strong></span></div></div></Container></section>
    <section className="context-band section section--ivory" aria-labelledby="context-title"><Container className="narrow-center"><p className="eyebrow">A comunidade já está no digital</p><h2 id="context-title">A informação da paróquia também precisa estar.</h2><p>Hoje, horários, eventos, avisos, pastorais e informações importantes muitas vezes ficam espalhados entre redes sociais, grupos de mensagens, arquivos e páginas desatualizadas.</p></Container></section>
    <section className="section section--ivory" aria-labelledby="pain-title"><Container><div className="section-heading"><p className="eyebrow">Uma realidade muito comum</p><h2 id="pain-title">Manter a presença digital de uma paróquia não deveria ser mais uma preocupação.</h2><p>A tecnologia deveria facilitar a comunicação da comunidade — não criar mais tarefas, dependências e dificuldades.</p></div><div className="icon-grid icon-grid--six">{cards(painPoints)}</div><p className="section-note">Foi olhando para essa realidade que nasceu o Católico Digital.</p></Container></section>
    <section className="section section--white" id="produto" aria-labelledby="solution-title"><Container className="solution-layout"><div className="solution-mockup product-preview product-preview--large" aria-hidden="true"><div className="device-window__bar"><span /><span /><span /></div><div className="solution-screen"><div /><div /><div /><div /><div /><div /></div></div><div className="section-heading section-heading--compact"><p className="eyebrow">Conheça o Católico Digital</p><h2 id="solution-title">Tudo o que a paróquia precisa para cuidar melhor da sua presença digital.</h2><p>O Católico Digital reúne informações e conteúdos em uma única estrutura, com um site atual, organizado e fácil de administrar.</p><p className="quote-line">A tecnologia cuida da complexidade para que a paróquia possa cuidar da comunicação.</p><div className="mini-feature-list"><span><LayoutDashboard aria-hidden="true" size={19} /> Um site profissional</span><span><Pencil aria-hidden="true" size={19} /> Fácil de atualizar</span><span><SlidersHorizontal aria-hidden="true" size={19} /> Adaptado à realidade da paróquia</span></div><Link className="text-link" href="#recursos">Ver os recursos <span aria-hidden="true">→</span></Link></div></Container></section>
    <section className="section section--cool" id="recursos" aria-labelledby="features-title"><Container><div className="section-heading"><p className="eyebrow">A paróquia escolhe o que precisa</p><h2 id="features-title">Uma estrutura que se adapta à realidade de cada comunidade.</h2><p>Nem toda paróquia precisa das mesmas coisas. O Católico Digital é organizado por recursos que podem ser utilizados conforme a necessidade.</p></div><div className="icon-grid icon-grid--five">{cards(features)}</div><div className="feature-callout"><SlidersHorizontal size={23} /><div><h3>Use apenas o que fizer sentido.</h3><p>Cada recurso pode ser ativado ou desativado conforme a realidade da paróquia.</p></div></div></Container></section>
    <section className="section section--white" id="como-funciona" aria-labelledby="steps-title"><Container><div className="narrow-center"><p className="eyebrow">Simples desde o começo</p><h2 id="steps-title">Sua paróquia no digital sem transformar isso em um projeto complicado.</h2></div><div className="steps-grid">{steps.map(([number, title, copy, Icon]) => <article className="step" key={number}><span className="step__number">{number}</span><span className="step__icon"><Icon aria-hidden="true" size={23} /></span><h3>{title}</h3><p>{copy}</p></article>)}</div></Container></section>
    <section className="section section--brand" aria-labelledby="benefits-title"><Container><div className="section-heading section-heading--light"><p className="eyebrow eyebrow--light">Mais do que um novo site</p><h2 id="benefits-title">Uma presença digital que trabalha a favor da comunidade.</h2></div><div className="icon-grid icon-grid--six benefits-grid">{cards(benefits)}</div></Container></section>
    <section className="section section--white" aria-labelledby="demo-title"><Container><div className="section-heading"><p className="eyebrow">Pensado para quem usa</p><h2 id="demo-title">Bonito para quem visita. Simples para quem administra.</h2><p>O Católico Digital funciona bem dos dois lados: para quem procura informações e para quem precisa mantê-las atualizadas.</p></div><ProductTabs tabs={tabs} /></Container></section>
    <section className="section section--ivory" id="para-quem" aria-labelledby="audience-title"><Container className="audience-layout"><div className="section-heading section-heading--compact"><p className="eyebrow">Será que é para a minha paróquia?</p><h2 id="audience-title">O Católico Digital pode ajudar especialmente se...</h2></div><ul className="check-list">{["Sua paróquia ainda não possui um site.", "O site existe, mas está antigo ou difícil de atualizar.", "A maior parte das informações está apenas nas redes sociais.", "A secretaria responde repetidamente às mesmas dúvidas.", "Poucas pessoas sabem atualizar os canais digitais.", "Vocês querem uma presença digital mais profissional sem aumentar a complexidade."].map(item => <li key={item}><Check size={19} aria-hidden="true" />{item}</li>)}</ul><Link className="button button--brand" href="#quero-conhecer">Quero conversar sobre minha paróquia</Link></Container></section>
    <section className="section section--white" aria-labelledby="purpose-title"><Container className="purpose-layout"><div className="purpose-image" aria-hidden="true"><div className="purpose-image__window"><Monitor size={30} /><span>comunidade no centro</span></div></div><div className="section-heading section-heading--compact"><p className="eyebrow">Tecnologia a serviço da comunidade</p><h2 id="purpose-title">Digitalizar não significa perder proximidade.</h2><p>O Católico Digital existe para facilitar o que a tecnologia pode organizar: informações, comunicação, acesso e presença digital.</p><blockquote>A tecnologia deve permanecer nos bastidores. A comunidade continua no centro.</blockquote></div></Container></section>
    <section className="section section--cool" id="seguranca" aria-labelledby="security-title"><Container><div className="section-heading"><p className="eyebrow">Responsabilidade digital</p><h2 id="security-title">Informações importantes merecem ser tratadas com cuidado.</h2><p>A estrutura é pensada desde o início com atenção à segurança, privacidade e boas práticas de proteção de dados.</p></div><div className="icon-grid icon-grid--four">{cards(security)}</div><Link className="text-link" href="/privacidade">Conheça nossa política de privacidade <span aria-hidden="true">→</span></Link></Container></section>
    <section className="section section--brand" aria-labelledby="difference-title"><Container className="difference-layout"><div className="section-heading section-heading--light section-heading--compact"><p className="eyebrow eyebrow--light">Não é apenas mais um template</p><h2 id="difference-title">Criado pensando na realidade de uma paróquia.</h2><p>Em vez de adaptar uma ferramenta genérica à realidade da Igreja, a estrutura já nasce pensando nas informações, rotinas e necessidades de uma comunidade paroquial.</p></div><div className="comparison"><div><h3>Site genérico</h3><p>Estrutura criada do zero</p><p>Recursos precisam ser adaptados</p><p>Manutenção fragmentada</p></div><div className="comparison__preferred"><h3>Católico Digital</h3><p>Estrutura preparada</p><p>Recursos paroquiais</p><p>Gestão simplificada</p></div></div></Container></section>
    <section className="section section--ivory" id="quero-conhecer" aria-labelledby="launch-title"><Container className="launch-card"><div className="section-heading section-heading--compact"><p className="eyebrow">Lançamento</p><h2 id="launch-title">Quer ser uma das primeiras paróquias a conhecer o Católico Digital?</h2><p>Estamos iniciando a apresentação para as primeiras comunidades. Deixe seus dados para entender a proposta e acompanhar o lançamento.</p></div><div className="launch-benefits"><p><Check size={18} /> Conheça a solução antes do lançamento público.</p><p><Check size={18} /> Converse diretamente sobre a realidade da sua paróquia.</p><p><Check size={18} /> Receba informações sobre condições e disponibilidade.</p></div><div className="form-wrapper"><h3>Conte um pouco sobre sua paróquia.</h3><p>Preencha os dados abaixo e entraremos em contato para apresentar melhor a proposta.</p><LeadForm /></div></Container></section>
    <section className="section section--white" id="duvidas" aria-labelledby="faq-title"><Container className="faq-layout"><div className="section-heading section-heading--compact"><p className="eyebrow">Dúvidas frequentes</p><h2 id="faq-title">O que você talvez queira saber antes de conversar conosco.</h2></div><FaqAccordion items={faq.map(([question, answer]) => ({ question, answer }))} /></Container></section>
    <section className="final-cta section section--night" aria-labelledby="final-title"><div className="final-cta__pattern" aria-hidden="true" /><Container className="narrow-center"><p className="eyebrow eyebrow--light">Católico Digital</p><h2 id="final-title">Uma presença digital mais simples para quem cuida da comunidade.</h2><p>Se sua paróquia quer organizar melhor suas informações e atualizar sua presença online, queremos conhecer sua realidade.</p><Link className="button button--gold" href="#quero-conhecer">Quero conhecer o Católico Digital</Link><br /><Link className="text-link text-link--light final-cta__secondary" href="/contato">Ainda tenho uma dúvida</Link></Container></section>
  </main>;
}
